### ISSUE TITLE
Cut sequence does not actually overwrite defaults

### ISSUE THREAD

**Issue by jpuritz** [dereneaton/simrrls#1]
Using the -c1 or -c2 option has no effect on output.

**Comment by dereneaton** [comment]
Thanks for finding this. It is now fixed. The cutter args are now merged into a single arg. You can use -c TGCAG,AATTC (comma separated, no space) to list two cutters for double digest. If your library type is single digest (e.g., RAD) the second cutter if present is ignored.

**Comment by jpuritz** [comment]
Happy to help.  This script is very useful!
