### ISSUE TITLE
AttributeError: 'module' object has no attribute 'simul'

### ISSUE THREAD

**Issue by cresnik** [dereneaton/simrrls#3]
Hi

I installed simrrls using egglib 3.0.0b5 as well as egglib 3.0.0b6. (tested and working according to the egglib homepage)
Running simrrls -h works but running the example usages always results in errors:

$ simrrls -o test1 -N 1e6 -n 4 -L 1000
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/simrrls_egglib_old/bin/simrrls", line 9, in <module>
    load_entry_point('simrrls==0.0.10', 'console_scripts', 'simrrls')()
  File "/usr/local/anaconda/envs/simrrls_egglib_old/lib/python2.7/site-packages/simrrls/**main**.py", line 17, in main
    run(params)
  File "/usr/local/anaconda/envs/simrrls_egglib_old/lib/python2.7/site-packages/simrrls/simrrls.py", line 464, in run
    tiptax, paramset = checkopts(params)
  File "/usr/local/anaconda/envs/simrrls_egglib_old/lib/python2.7/site-packages/simrrls/simrrls.py", line 29, in checkopts
    tiptax, paramset = defaulttree(params)
  File "/usr/local/anaconda/envs/simrrls_egglib_old/lib/python2.7/site-packages/simrrls/simrrls.py", line 87, in defaulttree
    paramset = egglib.simul.CoalesceParamSet(
AttributeError: 'module' object has no attribute 'simul'

Is this an actual error in the code or am I missing some files? I followed the installation steps outlined on the github page... the simrrls is installed an anaconda test environment.

Additional infos/versions:

$ python --version
Python 2.7.11 :: Continuum Analytics, Inc.

$ simrrls --version
simrrls 0.0.10

> > > import egglib
> > > print egglib.version
> > > 3.0.0b6

Does anybody else have this problem? Thanks for any hints....

**Comment by dereneaton** [comment]
It looks like the syntax changed for egglib v.3, which is super new and still apparently in beta testing. Sorry, I know egglib is a pain to install, but you'll have to go back to egglib v2 for simrrls to work.

**Comment by cresnik** [comment]
Hi
Thanks for the reply.
I re-installed simrrls using egglib 2.1.11 and it works now.

**Comment by ClaudiaPaetzold** [comment]
Hi,
I have run into the same problem.

When I call simrrls I get the following error message: 
$ simrrls
Traceback (most recent call last):
  File "/Users/ClaudiaPaetzold/anaconda2/bin/simrrls", line 9, in <module>
    load_entry_point('simrrls==0.0.10', 'console_scripts', 'simrrls')()
  File "build/bdist.macosx-10.5-x86_64/egg/simrrls/**main**.py", line 17, in main
  File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 464, in run
  File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 29, in checkopts
  File "build/bdist.macosx-10.5-x86_64/egg/simrrls/simrrls.py", line 87, in defaulttree
AttributeError: 'module' object has no attribute 'simul'

However, I have installed eggless v2.1.11. 
Any hints? 

P.S. python v 2.7
numpy v1.11.0

Thank You

**Comment by cresnik** [comment]
Hi Claudia

Not quite sure what could be wrong.
I've heard that Mac OS X comes with a slightly different python version 
compared to linux.
I don't have a Mac OS X 10.5 installation around somewhere, thus I can't 
really check this myself.

Please find below my installation notes. Maybe you can find out what is 
different compared to your setup or your installation...

notes:
1) the prefix during the egglib installation is because I didn't want to 
overwrite the system defaults
2) just "pip install ." in the simrrls folder didn't work for me, I had 
to use "pip install --upgrade ."
3) After creating the anaconda environment, the environment has to be 
initiated and all subsequent setup steps need to be executed within that 
environment

HTH
Chris

---

# cd /usr/local/anaconda/bin

# conda create -n simrrls python=2.7 numpy pip

--> installs the following dependencies:

```
 mkl:        11.3.1-0
 numpy:      1.11.0-py27_0
 openssl:    1.0.2g-0
 pip:        8.1.1-py27_1
 python:     2.7.11-0
 readline:   6.2-2
 setuptools: 20.7.0-py27_0
 sqlite:     3.9.2-0
 tk:         8.5.18-0
 wheel:      0.29.0-py27_0
 zlib:       1.2.8-0
```

#

# To activate this environment, use:

# $ source activate simrrls

#

# To deactivate this environment, use:

# $ source deactivate

#

""""""""""""""""""""""""""""""""""""""""

# source /usr/local/anaconda/bin/activate simrrls

# cd /usr/local/build

==== egglib v2.1.11 =====

see http://mycor.nancy.inra.fr/egglib/releases/2.1.11/egglib.pdf for 
installation

# mkdir /usr/local/egglib-2.1.11

# wget

http://mycor.nancy.inra.fr/egglib/releases/2.1.11/egglib-cpp-2.1.11.tar.gz

# wget

http://mycor.nancy.inra.fr/egglib/releases/2.1.11/egglib-py-2.1.11.tar.gz

# tar zxvf egglib-cpp-2.1.11.tar.gz

# tar zxvf egglib-py-2.1.11.tar.gz

# cd egglib-cpp-2.1.11

# ./configure --prefix=/usr/local/egglib-2.1.11

# make

# make install

# cd ..

# cd egglib-py-2.1.11

# python setup.py build --prefix=/usr/local/egglib-2.1.11

# python setup.py install --prefix=/usr/local/egglib-2.1.11

==== simrrls ====

# cd ..

# git clone https://github.com/dereneaton/simrrls.git

# cd simrrls

# pip install --upgrade .

---
